[package]
name = "r3_kernel"
version = "0.0.1"
authors = ["Narasimha1997 <yogaimpression@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = {version = "0.9.8"}

[package.metadata.bootimage]
build-command = ["xbuild"]
